### ISSUE TITLE
Canot auto start NGINX when reboot

### ISSUE THREAD

**Issue by conghai** [OzzyCzech/dotfiles#9]
**Your command** 
`ln -sfv /usr/local/opt/nginx/*.plist ~/Library/LaunchAgents`

> It will work when nginx run in port 8080, but not work for port 80. Because port 80 must to run with root user

**Solution (run NGINX on port 80):**
>sudo ln -sfv /usr/local/opt/nginx/*.plist /Library/LaunchDaemons
>sudo chmod 600 /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
>sudo chown root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
>sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.nginx.plist

**Comment by OzzyCzech** [comment]
I know... please checkout new version with brew services
